name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLUTTER_VERSION: "3.35.6"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Dependencies (app)
        working-directory: app
        run: flutter pub get
      - name: Dependencies (cargokit - rust_builder)
        working-directory: app/rust_builder/cargokit/build_tool
        run: flutter pub get
      - name: Remove gen directory (app)
        working-directory: app
        run: rm -rf lib/gen
      - name: Check format (app)
        working-directory: app
        run: dart format --set-exit-if-changed lib test

      - name: Dependencies (common)
        working-directory: common
        run: dart pub get
      - name: Check format (common)
        working-directory: common
        run: dart format --set-exit-if-changed lib test

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Dependencies (app)
        working-directory: app
        run: flutter pub get
      - name: Dependencies (cargokit - rust_builder)
        working-directory: app/rust_builder/cargokit/build_tool
        run: flutter pub get
      - name: Analyze (app)
        working-directory: app
        run: flutter analyze
      - name: Test (app)
        working-directory: app
        run: flutter test

      - name: Dependencies (common)
        working-directory: common
        run: dart pub get
      - name: Analyze (common)
        working-directory: common
        run: dart analyze
      - name: Test (common)
        working-directory: common
        run: dart test
